---
cifmw_snr_nhc_kubeconfig: "/home/{{ ansible_user | default('zuul') }}/.kube/config"
cifmw_snr_nhc_kubeadmin_password_file: "/home/{{ ansible_user | default('zuul') }}/.kube/kubeadmin-password"
cifmw_snr_nhc_namespace: openshift-workload-availability
cifmw_snr_nhc_cleanup_before_install: false
cifmw_snr_nhc_cleanup_namespace: false
cifmw_snr_nhc_retries: 10
cifmw_snr_nhc_delay: 15
