---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Label nodes in zones
  hosts: localhost
  tasks:
    - name: Get OpenShift access token
      register: _auth_results
      community.okd.openshift_auth:
        host: "{{ cifmw_openshift_api }}"
        username: "{{ cifmw_openshift_user }}"
        password: "{{ cifmw_openshift_password }}"
        validate_certs: false

# oc label nodes master-0 topology.kubernetes.io/zone=zoneA --overwrite
# oc label nodes master-1 topology.kubernetes.io/zone=zoneB --overwrite
# oc label nodes master-2 topology.kubernetes.io/zone=zoneC --overwrite
